// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Symbian Foundation License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.symbianfoundation.org/legal/sfl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//



/**
 @file
 @internalComponent - Internal Symbian test code
*/

#if !defined(__RULEBASEDUID_H__)
#define __RULEBASEDUID_H__

const TUid KUidApp1 = {0x1020D6FC};
const TUid KUidApp2 = {0x1020D6FD};
const TUid KUidApp3 = {0x1020D6FE};
const TUid KUidApp4 = {0X10210F77};

#endif
